### ISSUE TITLE
scrapy tests fail with queuelib 1.4.0

### ISSUE THREAD

**Issue by kmike** [scrapy/queuelib#11]
Hey @dangra, 

Scrapy tests start to fail after https://github.com/scrapy/queuelib/commit/89f6df01f1dc43b938243d9c3fa3aa75e5dddda2 (see https://travis-ci.org/scrapy/scrapy/jobs/79465256). It looks like a test-only issue: `.qdir` was renamed to `.qpath`.

What do you prefer - fix it in Scrapy (1.0 and master branches) or add .qdir alias to queuelib?

A part of the problem is that we're not running `trunk` tests for Scrapy on Travis; maybe we should start doing this (likely with failures allowed).

**Comment by dangra** [comment]
Depending on third party test suite doesn't look good but I readded it because of a different issue in https://github.com/scrapy/queuelib/commit/29d152c307420153232bedb72d6d7f8fdbccbc39#diff-147ad29ad4200eccfbf4f23ba8526119R8

**Comment by dangra** [comment]
Now it is passing, I fixed the references in scrapy source code.

**Comment by kmike** [comment]
:+1: 
> Depending on third party test suite doesn't look good

+1
