### ISSUE TITLE
In FifoDiskQueue, os.makedirs(path) occassionally fails with WindowsError [Error 5] in Windows

### ISSUE THREAD

**Issue by foresightyj** [scrapy/queuelib#9]
Here comes a windows-specific problem again. It is not be a big issue but I think it is worth letting you guys know.

I posted this question to stackoverflow, [see here](http://stackoverflow.com/questions/32243199/python-rapidly-creating-and-removing-directories-will-cause-windowserror-error?noredirect=1#comment52371092_32243199)

For the moment, I simply changed the line to:

```
try:
    os.makedirs(path)
except WindowsError as e:
    os.makedirs(path)
```

This will make it a hell of a lot better.

**Comment by dangra** [comment]
Such a good research on your SO question ! 

I think we can accept a windows only workaround for this issue even if it sucks, wrap os.makedirs with a function that handles all the windows quirks.

do you think retrying once is enough?

**Comment by foresightyj** [comment]
Definitely not, as I later found out in the log...

User eryksun in SO suggested the following script to print out the actual reason for the error:

    import ctypes
    ntdll = ctypes.WinDLL('ntdll')
    ntdll.RtlGetLastNtStatus.restype = ctypes.c_uint
    s = hex(ntdll.RtlGetLastNtStatus()); 
    print 'round', i, e, s; time.sleep(0.1)

I tried and it prints:

    round 875 [Error 5] : 'testingdir' 0xc0000056L. 

which is `STATUS_DELETE_PENDING`

Do you think it is a good idea to check if the `ntstatus` is STATUS_DELETE_PENDING, and if yes, proceed to repeatedly makedirs until no error ocurrs, possibly with a pause of 0.01s per loop and a maximum retry of 100?

Or, do you think it is better to do a `os.rename` to a uuid generated file name and then `os.remove` that directory?

**Comment by dangra** [comment]
I prefer the second option, retrying using `rename+rmdir` call in case of STATUS_DELETE_PENDING.

pseudo code:

```python
try:
   os.rmdir(path)
except WindowsError as exc:
   if exc is STATUS_DELETE_PENDING:
      os.rename(path, uuid)
      os.rmdir(uuid)
```

**Comment by foresightyj** [comment]
Right after `os.rmdir`, ntstatus is always `0x80000006L`(`STATUS_NO_MORE_FILES`). `STATUS_DELETE_PENDING` is only obtained after a failed `os.makedirs` call. With `os.rename` and then `os.remove`, we can ignore checking ntstatus totally. Simply renaming every time before we delete.

I have to apply this fix and see how it goes with my project. Will update a few days later if this approach works well.

**Comment by foresightyj** [comment]
Actually another user Tometzky who also answered my question in SO suggested writing a sqlite-version of queue which will probably more reliable in windows.

SQLite is also battery-included. May I know if you ever considered sqlite?

**Comment by dangra** [comment]
@foresightyj please take a look to #10, it implements persistent queue with sqlite.

**Comment by foresightyj** [comment]
Thanks a lot. I will switch to FifoSQLiteQueue.

**Comment by dangra** [comment]
queuelib v1.4.0 ships with *SQLiteQueue. I want to ask you to get back to this ticket later if you find problems or good results to share. thanks! :)

**Comment by dangra** [comment]
@foresightyj You can configure your Scrapy crawler to use a different disk queue with SCHEDULER_DISK_QUEUE setting.

    SCHEDULER_DISK_QUEUE = "queuelib.queue.FifoSQLiteQueue"

**Comment by lazem** [comment]
Hi 
I tried using FifoSQLiteQueue in scrapy configuration but I get the following trace in the first request it tries to push:

Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\scrapy\commands\crawl.py", line 58, in run
    self.crawler_process.start()
  File "C:\Anaconda2\lib\site-packages\scrapy\crawler.py", line 280, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "C:\Anaconda2\lib\site-packages\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
  File "C:\Anaconda2\lib\site-packages\twisted\internet\base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Anaconda2\lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Anaconda2\lib\site-packages\scrapy\utils\reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "C:\Anaconda2\lib\site-packages\scrapy\core\engine.py", line 134, in _next_request
    self.crawl(request, spider)
  File "C:\Anaconda2\lib\site-packages\scrapy\core\engine.py", line 209, in crawl
    self.schedule(request, spider)
  File "C:\Anaconda2\lib\site-packages\scrapy\core\engine.py", line 215, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "C:\Anaconda2\lib\site-packages\scrapy\core\scheduler.py", line 57, in enqueue_request
    dqok = self._dqpush(request)
  File "C:\Anaconda2\lib\site-packages\scrapy\core\scheduler.py", line 86, in _dqpush
    self.dqs.push(reqd, -request.priority)
  File "C:\Anaconda2\lib\site-packages\queuelib\pqueue.py", line 35, in push
    q.push(obj) # this may fail (eg. serialization error)
  File "C:\Anaconda2\lib\site-packages\queuelib\queue.py", line 201, in push
    raise TypeError('Unsupported type: {}'.format(type(item).__name__))
exceptions.TypeError: Unsupported type: dict

The enviroment is windows, using latest versions of both scrapy and queuelib. Any idea how to redeem this, make it work?
Thanks alot!

**Comment by Gallaecio** [comment]
@lazem If that still happens to you, please open a separate bug report.
